### PR TITLE
New function `merge_camtrapdp()`

### LINKED ISSUE #75: Create `merge()` to merge datasets
Note by @peterdesmet: see https://github.com/inbo/camtrapdp/issues/75#issuecomment-2142308577 for recent thoughts.

---

Quite often we want to merge the exports of several research projects (more and more for multi-site research), all using Camtrap-DP as export format, mostly all resulting from agouti.
Though manually this can be done by using several times read_camtrap_dp and subsequently merging the different resulting csv-files, I was wondering if it would not be better to add a function to camtraptor that automatically 

- [ ] merges different data packages resulting from read_camtrap_dp
- [ ] adds a column to the deployments.csv using the project_name as variable
- [ ] adds a column to the deployments.csv using the project location / study site 
- [ ] the function name could be "join_exports" or something similar but this I leave up to Peter :-)

### PR DESCRIPTION
**Pull request by sannegovaert**
fix #75

**Remarks**
- Assume that locationID's and individualID's must not be unique as the same location or individual can be used in different data packages.
- Assume that duplicatesd ID's are between packages, not within.
- If duplicates are present, all values of that identifier get a prefix.

**Helper functions**
I created 6 helper functions. Maybe they can be simplified or reduced in number!
They now live at utils.R. 

function | functionality in `merge_camtrapdp()` | suggestion
--- | --- | ---
`check_duplicate_ids()` | add prefix to identifiers with duplicates | helper function @ utils.R
`add_prefix()` | add prefix to identifiers with duplicates | helper function @ utils.R
`normalize_list()` | remove duplicated elements of lists | helper function @ utils.R or separate file.R
`is_subset()` | remove duplicated elements of lists  | helper function @ utils.R or separate file.R
`update_unique()` | remove duplicated elements of lists  | helper function @ utils.R or separate file.R
`remove_duplicates()` | remove duplicated elements of lists  | helper function @ utils.R or separate file.R

### CODE REVIEW

**Comment by peterdesmet** [comment]
- [ ] `references` is a character vector, cf. keywords. It is ok that there is no test for this.
- [ ] `description`: will have to think a bit more about this, for now it is fine to just paste the text together with a newline
- [ ] `project`: this needs an update in the standard. For now I would create a new property `projects`, which is a list containing the old projects. The `project` (singular) property can be removed (or we would have to generate one)
- [ ] Let's leave `name` and `title` empty (don't have the user set those in the function)
- [ ] Let's not generate an `id`. That also solves the problem of having meaningless `relatedIdentifiers`
- [ ] I would not create hash-based identifiers. Those have no relation with the original dataset and change every time the function is run. Rather, let's use [dplyr joins suffix](https://dplyr.tidyverse.org/reference/mutate-joins.html):as a function argument. If there are duplicates for an identifier, add suffices to all those identifiers with default `.x` and `.y`)

**Comment by sannegovaert** [comment]
> * [ ]  `references` is a character vector, cf. keywords. It is ok that there is no test for this.

In `example_dataset()` references is a(n empty) list, while keywords is indeed a character vector.

**Comment by sannegovaert** [comment]
I updated the PR. The main decision that remains is what kind of example we provide and how we test this function? Do we test it by merging (subsets of) example dataset, or by merging with a second example dataset?

**Comment by peterdesmet** [comment]
I would not create an additional example dataset (too much work to maintain). I suggest the following tests:

1. Combine example dataset twice
  - Fails because they have the same identifier
2. Combine example dataset twice, but with `id` updated to `1` and `2`
  - Metadata should largely remain the same (e.g. no duplicate contributors)
  - Data contains duplicates: 1 + 2 prefix
3. Combine example dataset twice, but without `id`
  - No test for metadata
  - Data contains duplicates: x + y prefix
4. Combine example dataset twice, but split in two first (deployment 1+2 and 3+4)
  - No test for metadata
  - Data should not contain duplicates
5. Combine example dataset + https://ipt.nlbif.nl/resource.do?r=awd_pilot2. It is small. Download (replace `resource` with `archive`) and unzip before running test.
  - Metadata should be mostly mutually exclusive
  - Data should not contain duplicates

**Comment by sannegovaert** [comment]
When merging the example dataset and the second data set, we have almost identical sources but a different version.

```
> x_merged$sources
[[1]]
[[1]]$title
[1] "Agouti"

[[1]]$path
[1] "https://www.agouti.eu"

[[1]]$email
[1] "agouti@wur.nl"

[[1]]$version
[1] "v3.21"


[[2]]
[[2]]$title
[1] "Agouti"

[[2]]$path
[1] "https://www.agouti.eu"

[[2]]$email
[1] "agouti@wur.nl"

[[2]]$version
[1] "v4"
```

It looks a bit weird, because it looks like a duplicate, but it is not really so.

**Comment by peterdesmet** [comment]
> we have almost identical sources but a different version.

That is fine, keep it as two sources.

**Review by PietrH — CHANGES_REQUESTED** [review]

**Comment by PietrH** [comment]
I only had a brief look, but an more in depth review of Peter is coming up.

**Comment by PietrH** [comment]
@peterdesmet : 0f9a28aac86b69a163bf45db34d2692eebb9fb0a, why remove the subdir in `tempdir()`? This guarantees that there are no filename collisions in `tempdir()` which is shared over the whole R session. 

- Avoids accidental collisions (usage of same filename) between tests
- Avoids collisions with developer writing to tempdir() 

Much less an issue for CI, but still, I'm interested to see what negatives you see

**Comment by PietrH** [comment]
> @PietrH regarding removing subdir
> 
>     * I assumed that `on.exit(unlink(temp_dir, recursive = TRUE))` clears everything from the tempdir after a test anyway? So collisions would only happen if a developer did not copy that line
> 
>     * The same subdir was used between tests, so collisions could happen anyway?
> 
> 
> My reasoning was mainly: only create subdirs if these is necessary _within_ a test.

Fair enough, I'm prefer leaving the clearing of the tempdir() up to the OS, and using `withr` if I really need to reset state. Since you could still leave tempdir() intact when a function fails before `unlink()` is called. `withr` really shines for things like environmental variables and (re)setting random seeds. I don't think it's use is warranted here.  My curiosity is satisfied!

**Review by peterdesmet — APPROVED** [review]

**Review by PietrH — APPROVED** [review]
I only checked my previous remarks. Well done Sanne! This wasn't an easy development :+1:

**Pull request merged**
