### PR TITLE
Fix #70

### LINKED ISSUE #70: create function get_custom_effort
function that calculates the effort for a specific time within the survey

variables are:

startdate (default = min startdate from all depl)
enddate (default = max enddate from all depl)
unit (hours, days, default = hours)
group_by(day, week, month, year -- default = null (total from startdata till enddata)

* returns the effort for each group_by in the chosen units

### PR DESCRIPTION
**Pull request by damianooldoni**
This PR adds function `get_custom_effort()` with related documentation and tests. See documentation via `?get_custom_effort` for details and run examples. 
@LynnINBO : could you please add yourself as contributor in DESCRIPTION? Thanks.

### CODE REVIEW

**Review by LynnINBO — APPROVED** [review]

**Review by LynnINBO — APPROVED** [review]

**Comment by damianooldoni** [comment]
It was late in the night for some extra notes 😴 

1. @LynnINBO counts the number of deployments, but I think we are not counting the number of deployments, but the effort (in days) over all deployments and one or more intervals. I say this because the camera operation matrix output is not an integer (0 or 1, deployment active or unactive) but a decimal number between 0 and 1 indicating the fraction of the day a deployment is active, i.e. the effort in days. This can be seen like a theoretical difference and maybe just a kind of name to give to the column, but a note worth.
2. The function returns always the three columns: `begin`, `effort`, `unit`. The `begin` column I find it important to make plots easily and to understand results easily even in table format.
3. @LynnINBO: thanks again for the draft: it was a very worth start point and you can recognize here and there your code in the actual version of `get_custom_effort`! I find important to underline the main difference which I think could implicate different results: as said in 1, I sum over all deployments in the given interval, (see [L177-L183](https://github.com/inbo/camtrapdp/blob/70-custom-trap-effort/R/get_custom_effort.R#L177-L183)), you do a tally which counting the number of rows (see in [draft:R124-R130](https://github.com/inbo/camtrapdp/pull/71/commits/ebbdc9be54e36d376c8b15f9c3d70cd4e7e3c08e#diff-743268c47fa7a0ea5a262ee6cbbef0c21690693d9bd5f0eb859775eb75573a1eR124-R130)). In this way you count decimal effort (partly day) as 1 (full day). Or am I wrong?

**Comment by LynnINBO** [comment]
@damianooldoni In the draft version I used `cameraOperation()`, and (correct me if I'm wrong) I don't think the final code has this function (couldn't see it in de `get_cam_op()`)? This gives 1 or NA if a deployment was active on a given day. I don't think it works with partial dates then? So when you `tally()` later on if only gives full days

**Review by LynnINBO — APPROVED** [review]

**Comment by damianooldoni** [comment]
Thanks, @LynnINBO! Interesting. `get_cam_op()` is the function I wrote to get the camera operation matrix starting from a datapackage. And it returns decimal numbers, indeed. I thought `cameraOperation()` did the same. 

Now I understand the reason you used `tally`, and you did it correctly 👍  I see you approved this PR: does this means you find summing up using decimal numbers for partial day efforts something good to have? IMO I like this way as the solution in the draft based on `cameraOperation `would always overestimate the effort for the start and end day of a deployment. Extreme, paradox case: we count 2 full days (effort = 2) if the interval includes the start at 23:59:59 and the end at 00:00:01, instead of counting it as 2 seconds! I think `get_custom_effort()` as I propose in this PR based on `get_cam_op()` improves this aspect.

I will add this in specific issue #52.

**Comment by LynnINBO** [comment]
@damianooldoni Well, decimal effort is the more correct way to calculate it (you're right that a 2 minute deployment would otherwise be counted as 2 days, which is major overetsimation), although trap effort is never reported like that -- they all report full days. I think it is good to keep decimal to be correct, but if used for reporting we could round up?

**Comment by damianooldoni** [comment]
@LynnINBO: thanks for exaplining me this! Yes, my idea is that the function should return things as correct as possible and rounding up should happen afterwards.
Just to be sure: a deployment from 23:59:59 to 00:00:01 (two seconds) is reported as 2 or as 0 (no full days present)?

**Comment by LynnINBO** [comment]
@damianooldoni I think in that case they would not report it, so 0. Unfortunately even trap effort is open to interpretation. The problem with decimal trap effort would be somewhat fixed by expressing it in hours, and then rounding those up?

**Comment by damianooldoni** [comment]
Yes, indeed. you can do it! Still, notice that there will be a little slight difference in situations like the example here below:

a deployment starts at 2pm and stops the day after at 4pm. No full days, but `get_effort()`  (and `get_custom_effort()`) would return 26 hours or 1.05 days depending on the unit. If you round up, you get 1 day. @LynnINBO: if you can live with this, I will merge the PR. let me know.

**Comment by LynnINBO** [comment]
@jimcasaer Any thoughts on this rounding question? Better for us to round up immediately, or leave it as decmal effort and let the people in question round as they see fit?

**Comment by jimcasaer** [comment]
My suggestion would be to return a default effort in hours.decimals and rounding on 2 decimal figures.
This allows afterwards the user to sum or multiply the resulting data 
Otherwise small rounding errors in the function can result in big errors down the road :-)

**Comment by damianooldoni** [comment]
Thanks @jimcasaer: well, I would not round at all, then! 😄  The point here is the fact that only full days are typically reported as @LynnINBO wrote (even if this is not a real standard!), while with this function partial days are counted as well, so that possible rounding at the end will not lead to same result in some cases (see my example above). 
But, as far as I can deduce from @jimcasaer's comment, it's not a problem to count partial days as well.

**Comment by jimcasaer** [comment]
@damianooldoni will I merge this pull request ?

**Pull request merged**
