### PR TITLE
Show deploys with no observations

### PR DESCRIPTION
**Pull request by damianooldoni**
This PR mainly solves #6 by showing deployments without observations in grey and showing `NA` as text while hovering over it with the mouse. Some other things done meanwhile:

1. remove unidentified species from the count: they count as 0
2. set color palette to blue scale as blue to better distinguish circles from standard leaflet background
3. add legend
3. add possibility to use an absolute color scale, sometimes could be useful for comparison reasons
4. add examples of all new functionalities in vignette

### CODE REVIEW

**Comment by jimcasaer** [comment]
@damianooldoni I was wondering if it would not be good to make the hovering showing location / month / year of the deployment as well as number of species 

same logic can later be extended to number observations / number of animals / RAI for a specific species

**Comment by damianooldoni** [comment]
@jimcasaer: yes, good idea. I will copy paste your comment to a new issue. This PR will be close very soon.

**Pull request merged**
