### PR TITLE
Use memoise to cache example_dataset

### LINKED ISSUE #66: Tests are slow because of `example_dataset()`, should we cache it?
Tests take 47 seconds on my system, almost all because `example_dataset()` is downloaded time and time again. 

I see some solutions:

**A.** We could only use it once in the tests, and reuse the object `example_dataset <- example_dataset()` , but that might cause trouble if we accidentally make changes to the `example_dataset` object. 

**B.** We could use some sort of caching:

- We could write our own caching mechanism, _how [hard](https://martinfowler.com/bliki/TwoHardThings.html) could it really be?_ 
- We could use memoisation, such as [memoise](https://memoise.r-lib.org/) 
- I've recently come across [roam](https://github.com/FinYang/roam)
- I know of: R.cache, cachem and storr, but haven't tried them: https://www.r-bloggers.com/2021/07/caching-the-results-of-functions-of-your-r-package/

**C.** Or we could wait 47 seconds...

ref: https://en.wikipedia.org/wiki/Memoization

### PR DESCRIPTION
**Pull request by peterdesmet**
Fix #66 by using `memoise` (from r-lib, only has 2 dependencies).

Reduces time for tests from 227s to 25s (on train wifi)

### CODE REVIEW

**Comment by PietrH** [comment]
We might want to consider implementing caching within `frictionless::read_package()`

**Comment by peterdesmet** [comment]
Indeed, do you mind creating an issue for that?

**Comment by PietrH** [comment]
I'll make one!

**Comment by PietrH** [comment]
We are getting an R CMD CHECK note: 

```
❯ checking dependencies in R code ... NOTE
  Namespace in Imports field not imported from: ‘memoise’
    All declared Imports should be used.
```

Because memoise is only used on package build-time, not within a function itself... (run time) That's what I get from this issue: https://github.com/hadley/r-pkgs/issues/203

I believe that this could lead to difficult to find bugs, but only if a user/contributor updates memoise between build-time and run-time. 

This was a problem within lubridate at one point, they don't have a memoise dependency and I can't immediately see how they got around it. 

One way I've found other packages getting around it is by importing the whole package within the function via `#' @import memoise`, this means the whole package is loaded on run-time. 

I'll make a suggestion in the review so you can compare both implementations.

**Comment by PietrH** [comment]
I can't use suggestions because there are no changes in NAMESPACE currently. I'll use a commit, but feel free to undo this commit if you don't like it.

**Comment by PietrH** [comment]
The tests are _much_ faster with caching implemented, 148-152s without caching vs 15-20s with caching. (on slow mobile internet). 

The speedup is much greater as what we could achieve by downloading the example dataset once per test, because it's only downloaded once when we use memoise.

**Comment by PietrH** [comment]
@peterdesmet , could you have a look what you think about using `@import memoise` ? I'm not 100% about the consequences.

**Review by PietrH — APPROVED** [review]

**Pull request merged**
