### PR TITLE
Solve #13

### PR DESCRIPTION
**Pull request by damianooldoni**
All functions now require a data package as input. See #13.
I also wrote an internal function `check_datapkg()` to check the data package structure and I use it at the beginning of all functions (`get_*` and `map_dep()`) as part of a defensive programming strategy.

/document
/style

### CODE REVIEW

**Comment by peterdesmet** [comment]
Shouldn’t this `check_datapkg` be used (only) when reading the camtrap-dp?

**Comment by damianooldoni** [comment]
These checks check the structure of the object returned by rread_camtrap-dp()`. So, when you use any of the other functions, you really want to be sure you use an object (list) with an expected structure, as returned by `read_camtrap-dp()`.
Everybody can make errors and so try to use the get_* functions or the visualization function `map_dep()` in the wrong way, e.g.
```r
get_n_species("this is not a datapkg")
get_n_species(list(a = 1, b = 2))
get_n_species(data.frame)
```
This means we need to check that the input of these functions the right object, as returned by `read_camtrap-dp()`.

About `read_camtrap-dp(), you are right, we need some checks there too, but these checks are slightly different, as they are not about the structure of a list, but about the presence of some files. Still, to be done as I had to focus first on visualization tools. And the check will probably be rewritten once #3 is solved.

**Comment by peterdesmet** [comment]
Ok, if the checks at the beginning of the other functions are minimal and light, I understand you want to bundle those in an internal function.

**Comment by damianooldoni** [comment]
Yes, @peterdesmet, quite minimal and light indeed. And, most of all, all the same so DRY principle forced me to bundle them in a function :+1: See  https://github.com/inbo/camtrapdp/blob/main/R/zzz.R#L1-L36 if you want to see the checks.

**Pull request merged**
