### PR TITLE
Fix #65

### LINKED ISSUE #65: Update package name: from datapackage to frictionless-r
The datapackage R package is now under the frictionless hat and is called `frictionless`. The previous inbo/datapackage repo (https://github.com/inbo/datapackage) points now to https://github.com/frictionlessdata/frictionless-r

We need to import it by `library(frictionless)`

### PR DESCRIPTION
**Pull request by damianooldoni**
Not much more than replacing inbo/datapackage with the new frictionless R package in DESCRIPTION. And update the related @importFrom in `read_camtrap_dp()` function. All tests work fine locally.

### CODE REVIEW

**Comment by damianooldoni** [comment]
@peterdesmet: no idea why checks are failing. Do you have one?

**Comment by peterdesmet** [comment]
I don’t know why they are failing. Maybe it is related to the dash in the repo name, but reverting to the old url (which will redirect) doesn’t work either. Maybe it is a caching issue?

**Comment by peterdesmet** [comment]
I think the error is related to pak. Can we temporarily disable this caching step in the GitHub Actions workflow?

**Comment by peterdesmet** [comment]
I've now tried in this in the gulltracking repo as a test (https://github.com/inbo/gulltracking/pull/34) but it fails there as well, so it is not an issue with pak.

Maybe the issue is that in `Imports` it notices the name `frictionless` but then it cannot find that in `Remotes`?

**Comment by peterdesmet** [comment]
Correction: it does seem to be related to pak. On gulltracking the (old `R-CMD-check`) actions without `pak` succeed, while the one with pak (`test-coverage`) doesn't: https://github.com/inbo/gulltracking/runs/4341640094

**Comment by ThierryO** [comment]
a possible solutions is to use the checklist machinery #67

**Comment by peterdesmet** [comment]
@ThierryO does checklist use `pak` in its GHA? I think it might be related to that (and automatically included when using usethis to make GH).

**Comment by ThierryO** [comment]
No. checklist doesn't use pak.

**Comment by damianooldoni** [comment]
Thanks @ThierryO for your help! Indeed, your package checklist will solve this issue with GitHub Actions and will sensibly improve the quality of the package metadata and structure. 
I will first pick up the needed changes about the GitHub Actions from your PR #67. Once this PR is merged to main I will try to find time to apply checklist and use it as you showed in your PR 👍 Thanks.

**Comment by ThierryO** [comment]
@damianooldoni Note that checklist requires the presence of an FOSS license. See https://github.com/inbo/checklist/issues/49#issuecomment-864957315

**Pull request merged**
